### ISSUE TITLE
Move from copr to CentOS repository (and building services, etc.)

### ISSUE THREAD

**Issue by mykaul** [Tendrl/tendrl2#26]
See https://github.com/Tendrl/tendrl-ansible/issues/107 - I've opened it on tendrl-ansible, but we should really do it for tendrl and then follow up with its Ansible installer.

**Comment by r0h4n** [comment]
Hey Yaniv,  I have filed an issue for this topic on correct repo 

https://github.com/Tendrl/tendrl-ci/issues/16

Lets discuss the topic there. This repo is mainly for code related to Tendrl + Gluster 4.0 (gd2)
